name: Run tests

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Use Node.js 20.15.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.1

      - name: Install Dependencies
      - run: npm ci
      - name: Run Tests
      - run: npm test
